spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: root
    password: 123456
    url: jdbc:mysql://192.168.1.103/wxsell?characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://127.0.0.1:3306/wxsell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell



#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F:\IDEAWorkSpace\wxsell\data
#  file: F:\IDEAWorkSpace\wxsell\data\sell.logdebug
#  level: info

